openapi: 3.0.3
info:
  title: roll_with_the_punches_ecommerce
  version: 1.0.0
  description: >-
    Roll with the Punches E-Commerce is an online retailer for all of the best
    boxing gear
  contact:
    name: Reed McDaniel
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /users/current:
    summary: User account details of currently logged in user
    get:
      summary: GET operation
      description: ""
      tags:
        - users
  /users/delete:
    summary: Delete currently logged in user
    post:
      summary: POST operation
      description: ""
      tags:
        - users
  /products:
    summary: Operations on all products
    get:
      summary: Get all products
      description: ""
      tags:
        - products
  /products/{id}:
    summary: Specific product by ID
    get:
      summary: Get a specific product by ID
      description: ""
      parameters:
        - $ref: "#/components/parameters/idParam"
      tags:
        - products
  /carts/manage:
    summary: Operations on user carts
    post:
      summary: Create, update, or deletion of user cart
      description: ""
      tags:
        - carts
  /carts/{user_id}:
    summary: Specific carst by user ID
    get:
      summary: Get a specific carts by user ID
      description: ""
      parameters:
        - $ref: "#/components/parameters/userIdParam"
      tags:
        - carts
  /checkout/{user_id}:
    summary: Checkout a cart
    post:
      summary: Initiate a checkout transaction
      description: Converts all carts for a user into an order
      parameters:
        - $ref: "#/components/parameters/userIdParam"
      tags:
        - checkout
  /orders/{user_id}:
    summary: Specific orders by user ID
    get:
      summary: Get history of all orders by user ID
      description: ""
      parameters:
        - $ref: "#/components/parameters/userIdParam"
      tags:
        - orders
components:
  parameters:
    idParam:
      name: id
      description: resource ID
      in: path
      required: true
      schema:
        type: string
    userIdParam:
      name: user_id
      description: user ID
      in: path
      required: true
      schema:
        type: string
